Thermal: introduce INT3406 thermal driver
On 11/30/2014 08:22 PM, Zhang Rui wrote:
> On Fri, 2014-11-07 at 15:11 -0400, Eduardo Valentin wrote:
>> Hi,
>>
>> On Tue, Oct 28, 2014 at 02:11:59PM +0800, Aaron Lu wrote:
>>> Jim found that the current kernel may trigger a build error with some
>>> config: drivers/built-in.o: In function `int3406_thermal_probe':
>>> int3406_thermal.c:(.text+0x1d10b8): undefined reference to
>>> `acpi_video_get_levels'. The problem happens when CONFIG_THERMAL=y and
>>> CONFIG_ACPI_VIDEO=m. Solve the problem by separating a kernel config for
>>> int3406 thermal driver and add dependency on ACPI video for it.
>>>
>>> Reported-by: Jim Davis <jim.epost@gmail.com>
>>> Signed-off-by: Aaron Lu <aaron.lu@intel.com>
>>
> Aaron, this is an incremental patch on top of the INT3406 driver patch.
> As, both patches have not been shipped in Linus' tree, please merge
> these two patches altogether and resend.

OK, here it is:

>From 02d7abdcfe138e6cdee7572b10addce4f56d89eb Mon Sep 17 00:00:00 2001
From: Aaron Lu <aaron.lu@intel.com>
Date: Wed, 3 Sep 2014 15:15:02 +0800
Subject: [PATCH] Thermal: introduce INT3406 thermal driver

INT3406 ACPI device object resembles an ACPI video output device, but its
_BCM is said to be deprecated and should not be used. So we will make
use of the raw interface to do the actual cooling. Due to this, the
backlight core has some modifications. Also, to re-use some of the ACPI
video module's code, one function has been exported.

Signed-off-by: Aaron Lu <aaron.lu@intel.com>
Signed-off-by: Zhang Rui <rui.zhang@intel.com>